In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,-1],[1,1,-3]]) # Python의 리스트로부터 Numpy

In [3]:
b = np.array([[3,2,-2],[-1,2,1]])

In [25]:
ApB = a+b

In [26]:
ApB

array([[ 4,  4, -3],
       [ 0,  3, -2]])

In [19]:
ApB[0][2]

-3

In [9]:
c = np.array([[3],[1],[2]])

In [13]:
ac = np.dot(a,c) # 곱셈을 하고 싶을때 a*c가 아니라 np.dot(a,c)이라는 형식으로 dot함수를 이용해야 한다.

In [16]:
ac

array([[ 3],
       [-2]])

In [17]:
ac[0][0]

3

In [20]:
d = np.array([[3,2],
              [1,1],
              [2,-1]])

In [23]:
ad = np.dot(a,d)

In [27]:
ad

array([[ 3,  5],
       [-2,  6]])

In [28]:
ad[0,1] # == ad[0][1]

5