In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
array1 > 4 # array1 중 4보다 큰 수

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False])

In [6]:
booleans = np.array([True,True,True,True,False,False,True])

In [8]:
a = np.where(booleans) # True 값의 인덱스를 가져온다.

In [9]:
a

(array([0, 1, 2, 3, 6], dtype=int64),)

In [13]:
print(a)

(array([0, 1, 2, 3, 6], dtype=int64),)


In [14]:
# b = np.array([1,2,2,3,3,4,4]) # 이해 잘못함

In [20]:
# np.where()