In [1]:
import numpy as np

In [4]:
A = np.array([[1,2,3],[-1,0,2],[3,4,5],[2,-2,-3]])

In [5]:
print(A)

[[ 1  2  3]
 [-1  0  2]
 [ 3  4  5]
 [ 2 -2 -3]]


In [6]:
B = np.array([[0,2],[1,-1],[3,-4]])

In [7]:
print(B)

[[ 0  2]
 [ 1 -1]
 [ 3 -4]]


In [15]:
A[2][1]

4

In [14]:
B[2][1]

-4