In [19]:
import numpy as np # numpy 불러오기 그리고 np 로 줄여부르기

In [27]:
array1 = np.array([2,3,5,7,11,13,17,19]) # numpy 모듈에서 array 함수 사용

In [28]:
print(array1)

[ 2  3  5  7 11 13 17 19]


In [4]:
type(array1) # ndarray 는 n차원배열을 의미함

numpy.ndarray

In [5]:
array1.shape # array1에 몇 개의 요소가 있는지 확인하기

(8,)

In [6]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [7]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
type(array2)

numpy.ndarray

In [9]:
array2.shape

(3, 4)

In [10]:
array2.size

12

In [11]:
# 실습

In [12]:
array1 = np.full(6,0)
array2 = np.random.random(6)

In [13]:
array1

array([0, 0, 0, 0, 0, 0])

In [14]:
array2

array([0.34684475, 0.02822388, 0.90118754, 0.514611  , 0.71715277,
       0.20082221])

In [15]:
array3 = np.array((1,2,3)) # 소괄호를 써도 리스트형으로 출력됨

In [16]:
array3

array([1, 2, 3])

In [20]:
array3[0]

1

In [24]:
array4 = np.array({1,2,3})

In [25]:
array4

array({1, 2, 3}, dtype=object)