In [1]:
import numpy as np

In [2]:
array1 = np.array([14,6,13,21,23,31,9,5])

In [4]:
print(array1.mean()) # 평균값

15.25


In [5]:
print(array1.max()) # 최댓값

31


In [6]:
print(array1.min()) # 최솟값

5


In [7]:
array2 = np.array([8,12,9,15,16])
array3 = np.array([14,6,13,21,23,31,9,5])

In [9]:
print(np.median(array2)) # 중앙값 리스트의 갯수가 홀수라면 리스트를 순차적으로 나열했을때의 리스트 중앙에 있는 값
print(np.median(array3)) # 리스트의 갯수가 짝수라면 중앙에 있는 값 두개를 더해서 2로 나눈 값

12.0
13.5


In [32]:
c = np.array([[[0,1,3],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]]) # 3중 리스트로 3차원의 배열

In [47]:
c

array([[[ 0,  1,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [48]:
print(c[0])
print()
print(c[1])

[[0 1 3]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [49]:
print(c[0][0])
print()
print(c[0][1])

[0 1 3]

[3 4 5]


In [42]:
c[0][0][0]

0

In [15]:
d = np.zeros(8) # 0이 8개 저장된 배열
print(d)

e = np.ones(8) # 1이 8개 저장된 배열
print(e)

f = np.arange(8) # 0부터 7까지 저장된 배열
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [22]:
a = np.array([[0,1,2],
                [3,4,5]]) # 2x3의 2차원 배열

In [23]:
print(np.shape(a)) # a의 형태를 표시

(2, 3)


In [24]:
print(len(a)) # a의 '행' 수를 얻는다

2


In [25]:
print(a)
print()
print(a + 3)
print()
print(a * 3)

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


In [27]:
b = np.array([[1,2,3],[4,5,6]]) # 2차원 배열
c = np.array([[2,3,1],[6,4,5]]) # 2차원 배열
print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)

[[1 2 3]
 [4 5 6]]

[[2 3 1]
 [6 4 5]]

[[ 3  5  4]
 [10  9 11]]

[[ 2  6  3]
 [24 20 30]]


In [50]:
a = np.array([1,2,3,4,5])
print(a[3])

4


In [52]:
a[2] = 9
print(a)

[1 2 9 4 5]


In [53]:
b = np.array([[0,1,2],[3,4,5]])
print(b[1,2]) # b[1][2]와 같다
print(b[1][2])

5
5


In [55]:
b[1,1] = 9
b[1][2] = 8
print(b)

[[0 1 2]
 [3 9 8]]


In [58]:
c = np.array([[0,1,2],
              [3,4,5]])
print(c[1,:]) # 인덱스가 1인 행을 취득
print()
c[:,1] = np.array([6,7]) # 인덱스가 1인 열을 취득한 후 그 값을 6과 7로 바꿈
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


In [74]:
a = np.array([[0,1,2],[3,4,5]])
print("합계 : %d"%np.sum(a))
print("평균 : %0.3f"%np.average(a))
print("최댓값 : %d"%np.max(a))
print("최솟값 : %d"%np.min(a))
print("mean : %0.3f"%np.mean(a))

합계 : 15
평균 : 2.500
최댓값 : 5
최솟값 : 0
mean : 2.500


In [66]:
a = np.array([[0,1,2],[3,4,5]])
b = np.array([[5,4,3],[2,1,0]])
print(a+b) # 합
print()
print(a-b) # 차
print()
print(a*b) # 곱

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]


In [68]:
a = np.array([[0,1,2],[3,4,5]])
b = np.array([[2,1],[2,1],[2,1]])
print(np.dot(a,b))

[[ 6  3]
 [24 12]]


In [69]:
c = np.array([[0,1,2],[3,4,5],[6,7,8]])
d = np.array([[0,2,0],[2,0,2],[0,2,0]])
print(np.dot(c,d))

[[ 2  4  2]
 [ 8 16  8]
 [14 28 14]]
